public enum LogMsg {


    SUCCESS("SUCCESS"),
    INVALID_ARGUMENTS("INVALID_ARGUMENTS"),
    FAILED_TO_WRITE("FAILED_TO_WRITE"),
    FAILED_TO_READ("FAILED_TO_READ"),
    INVALID_INPUT_STREAM("INVALID_INPUT_STREAM"),
    INVALID_OUTPUT_STREAM("INVALID_OUTPUT_STREAM"),
    CONFIG_GRAMMAR_ERROR("CONFIG_GRAMMAR_ERROR"),
    CONFIG_SEMANTIC_ERROR("CONFIG_SEMANTIC_ERROR"),
    FAILED_PIPELINE_CONSTRUCTION("FAILED_PIPELINE_CONSTRUCTION"),
    NOT_FOUND_TOKEN("NOT_FOUND_TOKEN: "),

    NO_CONFIG_FILE("NO_CONFIG_FILE"),
    FILE_NOT_FOUND("FILE_NOT_FOUND"),
    INVALID_CONFIG_DATA("INVALID_CONFIG_DATA"),
    START_PARS("START_PARS"),

    INVALID_EXPRESSION("INVALID_EXPRESSION"),
    TRY_CREATE_WORKER("TRY_CREATE_WORKER"),
    INCOMPATIBLE_INPUT_AND_OUTPUT_TYPES("INCOMPATIBLE_INPUT_AND_OUTPUT_TYPES");

    public final String msg;

    LogMsg(String msg) {
        this.msg = msg;
    }
}

